# Generated by Django 6.0.3 on 2026-03-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.URLField(max_length=1000),
        ),
    ]
